# Generated by Django 5.2.5 on 2025-08-13 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('path', models.TextField()),
                ('body_hash', models.CharField(max_length=64)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('content_type', models.CharField(default='application/json', max_length=100)),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_idempotency_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_idempo_user_id_aa987a_idx'), models.Index(fields=['created_at'], name='core_idempo_created_bb3e28_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'key', 'method', 'path', 'body_hash'), name='unique_idempotency_request_tuple')],
            },
        ),
    ]
