# Generated by hand for Task B (soft-delete); run makemigrations to regenerate if needed.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nursery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="is_deleted",
            field=models.BooleanField(default=False, db_index=True),
        ),
        migrations.AddField(
            model_name="plant",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="propagationbatch",
            name="is_deleted",
            field=models.BooleanField(default=False, db_index=True),
        ),
        migrations.AddField(
            model_name="propagationbatch",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="plant",
            index=models.Index(fields=["user", "is_deleted"], name="nursery_plant_user_is_deleted_idx"),
        ),
        migrations.AddIndex(
            model_name="propagationbatch",
            index=models.Index(fields=["user", "is_deleted"], name="nursery_batch_user_is_deleted_idx"),
        ),
    ]
